import type { Metadata } from 'next'
import { Montserrat, Roboto } from 'next/font/google'

import './globals.scss'

const montserrat = Montserrat({ subsets: ['latin'] })
const roboto = Roboto({ weight: ['400'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
